<a href="https://colab.research.google.com/github/Sujay-510/Numpy-exercise/blob/main/Exercise0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# SOME NUMPY EXERCISE FOR BEGINNER

In [ ]:
import numpy as np
a=np.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
a=str(input("ENTER A STRING: "))
b=str(input("ENTER A STRING: "))
c=str(input("ENTER A STRING: "))
d=str(input("ENTER A STRING: "))
e=str(input("ENTER A STRING: "))
f=str(input("ENTER A STRING: "))
print(a.lower())
print(b.upper())
print(len(c))
print(d.casefold())
print(e.islower())
print(f.isnumeric())

ENTER A STRING: HII
ENTER A STRING: hello
ENTER A STRING: thats awsome
ENTER A STRING: ohh yaa thats cool
ENTER A STRING: my turn ok ?
ENTER A STRING: yesssssssssss55656
hii
HELLO
12
ohh yaa thats cool
True
False


In [ ]:
for i in range(6):
  print(i)

0
1
2
3
4
5


In [ ]:
r=2
while(r<10):
  print(r)
  r+=1

2
3
4
5
6
7
8
9


In [ ]:
print(a)

[1 2 3]


In [ ]:
b=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(b)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [ ]:
b[1,:]

array([ 7,  8,  9, 10, 11, 12])

In [ ]:
b[1,2]

9

In [ ]:
b[1,2]=12
print(b)
b[1,2]=9
print(b)

[[ 1  2  3  4  5  6]
 [ 7  8 12 10 11 12]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [ ]:
a.dtype
a.size*a.itemsize
a.itemsize
a.ndim
b.ndim
print(b)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [ ]:
b[1,1:5:1] #getting the rw and elements in sequences

10

In [ ]:
b[:5]

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [ ]:
c=np.array([[1,2,3,4,5,6,7,8,9,],[12,13,14,15,16,17,18,19]])
print(c)

[list([1, 2, 3, 4, 5, 6, 7, 8, 9]) list([12, 13, 14, 15, 16, 17, 18, 19])]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  """Entry point for launching an IPython kernel.


Some Numpy Examples

In [ ]:
c=np.array([[[1,2,3],[4,5,6],[4,3,2]],[[7,1,9],[7,8,9],[4,8,9]]])
print(c)

[[[1 2 3]
  [4 5 6]
  [4 3 2]]

 [[7 1 9]
  [7 8 9]
  [4 8 9]]]


In [ ]:
c[0,:,:]

array([[1, 2, 3],
       [4, 5, 6],
       [4, 3, 2]])

In [ ]:
np.full((5,5),1)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
z=np.full((3,3),0)
print(z)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
np.full((3,8),2)

array([[2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2]])

In [ ]:
c = np.zeros((1,2,4))
print(c)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [ ]:
form = np.full_like(c,6)
print(form)

[[[6. 6. 6. 6.]
  [6. 6. 6. 6.]]]


In [ ]:
form[:,0]

array([[6., 6., 6., 6.]])

In [ ]:
d = np.array([[1,2,3,5],[4,5,6,4],[8,9,0,3],[11,12,13,2]])
print(d)

[[ 1  2  3  5]
 [ 4  5  6  4]
 [ 8  9  0  3]
 [11 12 13  2]]


In [ ]:
d[1:3,1:3]=[(6,5),(52,36)]
print(d)

[[ 1  2  3  5]
 [ 4  6  5  4]
 [ 8 52 36  3]
 [11 12 13  2]]


In [ ]:
e = np.ones((5,5))
print(e)

z = np.zeros((3,3))
print(z)
z[1,1] = 9
print(z)

e[1:4,1:4] = z
print(e)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
#designing such a 3*3 matrix withalmost every different element 
x = np.full((3,3),1)
print(x)
x[0:3,0:3] = ((1,2,3),(4,5,6),(7,8,9))
print(x)

[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
v = np.repeat(x,2,axis=1)
print(v)

[[1 1 2 2 3 3]
 [4 4 5 5 6 6]
 [7 7 8 8 9 9]]


In [ ]:
if():
  file = np.genfromtxt('./exercise.txt', delimiter=',')
  open("./exercise.txt")

In [ ]:
d = np.zeros(10)
print(d)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
